plugins {
    id 'application'
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    implementation "com.badlogicgames.gdx:gdx:1.14.2"
    implementation "com.badlogicgames.gdx:gdx-platform:1.14.2:natives-desktop"
    implementation "com.badlogicgames.gdx:gdx-backend-headless:1.14.2"
}

application {
    mainClass = 'com.example.sim.SimMain'
}
