version = "1.0"

[metadata]
tags = ["docling"]

[environment]
build_timeout_sec = 3600.0
allow_internet = true
memory_mb = 3072
mcp_servers = []

[environment.env]


[agent]
timeout_sec = 3600.0

[verifier]
timeout_sec = 3600.0

[verifier.env]


[solution.env]

