plugins {
    id 'application'
    id 'java'
}

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

application {
    mainClass = 'com.example.Main'
    applicationDefaultJvmArgs = ['-Djava.awt.headless=true']
}

dependencies {
    implementation 'com.badlogicgames.gdx:gdx:1.14.2'
    implementation 'com.badlogicgames.gdx:gdx-backend-headless:1.14.2'
    implementation 'com.badlogicgames.gdx:gdx-platform:1.14.2:natives-desktop'
}

run {
    standardInput = System.in
}
