version = "1.0"

[metadata]
tags = ["wasp", "agent_verification"]

[environment]
memory_mb = 2048
build_timeout_sec = 600.0
allow_internet = true
mcp_servers = []

[environment.env]


[agent]
timeout_sec = 600.0

[verifier]
timeout_sec = 600.0

[verifier.env]
POCHI_API_KEY = "${POCHI_API_KEY}"

[solution.env]

