version = "1.0"

[metadata]
tags = ["gel"]

[environment]
build_timeout_sec = 600.0
allow_internet = true
mcp_servers = []
memory_mb = 4096

[environment.env]


[agent]
timeout_sec = 600.0

[verifier]
timeout_sec = 600.0

[verifier.env]


[solution.env]

