apply plugin: 'application'

dependencies {
    implementation project(':core')
    implementation "com.badlogicgames.gdx:gdx:${gdxVersion}"
    implementation "com.badlogicgames.gdx:gdx-backend-headless:${gdxVersion}"
}

application {
    mainClass = 'com.combodetector.headless.Main'
}

run {
    if (project.hasProperty('args')) {
        args project.property('args').split('\\s+')
    }
    standardInput = System.in
}
