buildscript {
    repositories {
        mavenCentral()
    }
}

allprojects {
    apply plugin: 'eclipse'
    apply plugin: 'idea'

    ext {
        gdxVersion = '1.14.2'
    }
}

subprojects {
    apply plugin: 'java-library'

    repositories {
        mavenCentral()
        maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url "https://oss.sonatype.org/content/repositories/releases/" }
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}
