version = "1.0"
[metadata]
[verifier]
timeout_sec = 600.0
[agent]
timeout_sec = 600.0
[environment]
build_timeout_sec = 600.0
cpus = 4
memory_mb = 8192
storage_mb = 10240
gpus = 0
allow_internet = true
mcp_servers = []
[environment.env]
POCHI_API_KEY = "${POCHI_API_KEY}"
POCHI_LOG = "debug"
[verifier.env]
POCHI_API_KEY = "${POCHI_API_KEY}"
POCHI_LOG = "debug"
[solution.env]
