plugins {
    id 'java'
    id 'application'
}

sourceCompatibility = 17
targetCompatibility = 17

dependencies {
    implementation "com.badlogicgames.gdx:gdx:1.14.2"
    implementation "com.badlogicgames.gdx:gdx-backend-headless:1.14.2"
    implementation "com.badlogicgames.gdx:gdx-platform:1.14.2:natives-desktop"
}

application {
    mainClass = 'com.quadtree.headless.HeadlessLauncher'
}

run {
    standardInput = System.in
}
