version = "1.0"

[metadata]
tags = ["typesense"]

[environment]
build_timeout_sec = 600.0
allow_internet = true
mcp_servers = []

[environment.env]

[agent]
timeout_sec = 600.0

[verifier]
timeout_sec = 600.0

[verifier.env]

[solution.env]
