version = "1.0"

[metadata]
tags = ["gel"]

[environment]
build_timeout_sec = 1800.0
memory_mb = 4096
allow_internet = true
mcp_servers = []

[environment.env]


[agent]
timeout_sec = 3600.0

[verifier]
timeout_sec = 1800.0

[verifier.env]


[solution.env]

