version = "1.0"

[metadata]
tags = ["capacitor"]

[environment]
build_timeout_sec = 3600.0
cpus = 4
memory_mb = 12288
storage_mb = 20480
gpus = 0
allow_internet = true
mcp_servers = []

[environment.env]
POCHI_API_KEY = "${POCHI_API_KEY}"


[agent]
timeout_sec = 1800.0

[verifier]
timeout_sec = 1800.0

[verifier.env]


[solution.env]

