version = "1.0"

[metadata]
tags = ["prisma"]

[environment]
build_timeout_sec = 600.0
allow_internet = true
mcp_servers = []

[environment.env]
# Add more environment variables requried

[agent]
timeout_sec = 600.0

[verifier]
timeout_sec = 600.0

[verifier.env]
# Add more environment variables requried

[solution.env]
